### ISSUE TITLE
why apply ridge regularization on output layer?

### ISSUE THREAD

**Issue by WuYunjin** [icc2115/Neural-GC#2]
Hi,
It's a great implementation, but I noted the Loss function in the code is the MSE + ridge + nonsmooth, and in the paper, the Loss function seems to be the MSE + nonsmooth.
What is the ridge? I saw the comment"Apply ridge penalty at linear layer" in clstm.py and "Apply ridge penalty at all subsequent layers" in cmlp.py, but still not sure why the ridge penalty is needed?

Thanks,
Yunjin

**Comment by icc2115** [comment]
Hi - that's a good question, we didn't discuss this additional penalty in the paper.

The problem is that with the `MSE + non-smooth` loss function, there's a penalty encouraging the first layer's weights to be small, while the next layer's weights aren't penalized at all. That's bad, because you can end up with a model where the first layer's weights are very small, and not necessarily sparse (containing many zeros), but the next layer's weights are very big. So we use the ridge penalty to ensure that the other layer's weights don't get too large.

In our experiments, we tend to fix the ridge penalty to a small value, and only change the non-smooth penalty to find different levels of sparsity. Let me know if this makes sense.

Ian
